export const FORBIDDEN_TOKENS = {
  background: [
    "fondo negro",
    "black background",
    "dark background",
    "matte black",
    "fondo oscuro",
    "background oscuro",
    "vignette",
    "degradado",
    "gradient",
    "gris oscuro",
    "dark vignette",
    "black backdrop",
  ],
  render: [
    "vector",
    "vectorial",
    "3d",
    "cgi",
    "render",
    "photorealistic",
    "premium",
    "minimalismo",
    "sketch",
    "watercolor",
    "cartoon",
    "comic",
    "flat design",
    "oil painting",
    "line art",
    "anime",
  ],
  lighting: [
    "dramatic lighting",
    "studio light",
    "studio lighting",
    "golden hour",
    "soft shadows",
    "hard shadows",
    "cinematic",
    "bokeh",
    "macro",
    "wide angle",
    "4k",
    "high definition",
    "high clarity",
    "chiaroscuro",
    "volumetric",
    "volumetric light",
  ],
} as const;

export const FORBIDDEN_TOKEN_GROUPS: Record<string, string[]> = {
  background: [...FORBIDDEN_TOKENS.background],
  render: [...FORBIDDEN_TOKENS.render],
  lighting: [...FORBIDDEN_TOKENS.lighting],
};

export const ALL_FORBIDDEN_TOKENS: string[] = [
  ...FORBIDDEN_TOKENS.background,
  ...FORBIDDEN_TOKENS.render,
  ...FORBIDDEN_TOKENS.lighting,
];
